import { CHARACTERS_REJECT,
    FETCH_CHARACTERS,
    PENDING_CHARACTERS,
    FETCH_SINGLECHARACTER,
    PENDING_SINGLEPLAYER,
    SINGLECHARACTER_REJECT, 
    RESET_DATA, 
    CHANGE_PARAMS, 
    LOAD_MORE_DATA } from '../types/characterTypes'